version: "3.9"

services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www
        command: php artisan serve --host=0.0.0.0 --port=8000
        ports:
            - "8000:8000"
        depends_on:
            - soketi

    scheduler:
        build: .
        container_name: laravel_scheduler
        volumes:
            - .:/var/www
        depends_on:
            - app
        restart: unless-stopped
        # Run Laravel schedule in a loop every minute
        command: >
            sh -c "while true; do php /var/www/artisan schedule:run --verbose --no-interaction; sleep 60; done"

    soketi:
        image: quay.io/soketi/soketi:latest
        container_name: soketi
        ports:
            - "6001:6001"
            - "9601:9601"
        environment:
            DEBUG: "soketi:*"
            SOKETI_HOST: "0.0.0.0"
            SOKETI_PORT: 6001
            SOKETI_DEFAULT_APP_ID: "954259"
            SOKETI_DEFAULT_APP_KEY: "34bt7ihktudxw8thfeuy"
            SOKETI_DEFAULT_APP_SECRET: "zqpnx8kyicks2t3nf8cn"
            SOKETI_METRICS_SERVER_PORT: 9601
        restart: unless-stopped
